---
Name:  'easyiotsharp'

Host: '106.75.118.194:5999'


Mqtt:
  Host: 82.156.125.76
  Port: 1883
  ClientId: EasyIotSharp_DataProcessor
  Username: admin 
  Password: ZTXH2025!@# 
  TopicFormat: "{0}/{1}/rawdata"

Storage: 
  Elasticsearch:
    - 'http://106.75.84.97:9200'
  MysqlServers:  '82.156.125.76:3306'
  MysqlConnectionMode: ''
  MysqlDbName:  'easyiotsharp'
  MysqlUsername:  'root'
  MysqlPassword:  'jichang2025!@#'
  InfluxdbServers: '82.156.125.76:8086'
  InfluxdbConnectionMode: ''
  InfluxdbName: 'db_sports_center'
  InfluxdbUsername: 'jsuper'
  InfluxdbPassword: 'jsuper[admin]'

Caching:
  IsOpen: true
  RedisEnabled:  true
  RedisConnStr: '106.75.84.97:6379,password=i&@D04oK,SyncTimeout=5000,allowAdmin=true'
  RedisTwemProxyEnabled: false
  RedisDatabaseId:  2

ESPagging:
  MaxReadCount: 10000
  MaxWriteCount: 1000