---
Name:  'easyiotsharp'

Host: '106.75.118.194:5999'

Storage: 
  Elasticsearch:
    - 'http://106.75.84.97:9200'
  MysqlServers:  '117.50.11.43:27019'
  MysqlConnectionMode:
  MysqlDbName:  'youzy_easyiotsharp'
  MysqlUsername:  'root'
  MysqlPassword:  '6d77cXXs1s1pFsaLiLoNgET8LzLj27'

Caching:
  IsOpen: true
  RedisEnabled:  true
  RedisConnStr: '10.10.138.209:6379'
  RedisTwemProxyEnabled: false
  RedisDatabaseId:  1

ESPagging:
  MaxReadCount: 10000
  MaxWriteCount: 1000