Mqtt:
  Host: 82.156.125.76
  Port: 1883
  ClientId: EasyIotSharp_DataProcessor
  Username: admin 
  Password: ZTXH2025!@# 
  TopicFormat: "{0}/{1}/rawdata"
Serilog:
  Using:
  - Serilog.Sinks.Console
  MinimumLevel:
    Default: Information
    Override:
      Microsoft: Warning
      Microsoft.Hosting.Lifetime: Information
      Microsoft.AspNetCore.Hosting.Diagnostics: Warning
      System: Warning
      Exceptionless.Web.Security.ApiKeyAuthenticationHandler: Warning
      Foundatio.Utility.ScheduledTimer: Warning
      Foundatio.Metrics: Warning
  WriteTo:
  - Name: Console
  Enrich:
  - FromLogContext
  - WithMachineName
  - WithThreadId