---
Name:  'easyiotsharp'

Host: '106.75.118.194:5999'


# 在现有配置的基础上添加以下内容
Mqtt:
  Host: 82.156.125.76
  Port: 1883
  ClientId: EasyIotSharp_DataProcessor
  Username: admin # 如果需要认证，请填写用户名
  Password: ZTXH2025!@# # 如果需要认证，请填写密码
  TopicFormat: "{0}/{1}/rawdata" # {0}=项目ID, {1}=传感器ID

Storage: 
  Elasticsearch:
    - 'http://106.75.84.97:9200'
  MysqlServers:  '82.156.125.76:3306'
  MysqlConnectionMode: ''
  MysqlDbName:  'easyiotsharp'
  MysqlUsername:  'root'
  MysqlPassword:  'jichang2025!@#'
  InfluxdbServers: '82.156.125.76:8086'
  InfluxdbConnectionMode: ''
  InfluxdbName: 'db_sports_center'
  InfluxdbUsername: 'jsuper'
  InfluxdbPassword: 'jsuper[admin]'

Caching:
  IsOpen: true
  RedisEnabled:  true
  RedisConnStr: '10.10.138.209:6379'
  RedisTwemProxyEnabled: false
  RedisDatabaseId:  1

ESPagging:
  MaxReadCount: 10000
  MaxWriteCount: 1000