---
Name:  'easyiotsharp.admin'

Host: '106.75.118.194:5999'

Storage: 
  Elasticsearch:
    - 'http://106.75.84.97:9200'
  MysqlServers:  '117.50.11.43:27019'
  MysqlConnectionMode:
  MysqlDbName:  'youzy_easyiotsharp'
  MysqlUsername:  'root'
  MysqlPassword:  '6d77cXXs1s1pFsaLiLoNgET8LzLj27'

Caching:
  IsOpen: true
  RedisEnabled:  true
  RedisConnStr: '106.75.84.97:7369,password=i&@D04oK,SyncTimeout=5000,allowAdmin=true'
  RedisTwemProxyEnabled: false
  RedisDatabaseId:  2